# Generated by Django 2.2.3 on 2020-04-15 16:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DiaryDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2020, 4, 15, 19, 8, 49, 259221))),
                ('work_info', models.CharField(default='', max_length=5000)),
                ('is_complete', models.BooleanField(default=False)),
                ('liked_things', models.TextField(default='')),
                ('disliked_things', models.TextField(default='')),
                ('day_evaluation', models.IntegerField(blank=True, choices=[(1, 'Понравилось'), (2, 'Не понравилось'), (3, 'Нейтрально')], null=True, verbose_name='Day evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_type', models.CharField(choices=[('Учебная', 'Учебная'), ('Производственная', 'Производственная')], max_length=30, verbose_name='Type')),
                ('practice_addres', models.CharField(default='', max_length=500)),
                ('date_start', models.DateField(default=datetime.datetime(2020, 4, 15, 19, 8, 49, 330771))),
                ('date_end', models.DateField(default=datetime.datetime(2020, 4, 15, 19, 8, 49, 330800))),
                ('diary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='practice.Diary')),
            ],
        ),
    ]
