# Generated by Django 2.2.3 on 2020-05-10 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassicDiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Дневник без gamification и без mindfullness',
                'verbose_name_plural': 'Дневники без gamification и без mindfullness',
            },
        ),
        migrations.CreateModel(
            name='ClassicDiaryDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2020, 5, 10, 18, 25, 6, 261523))),
                ('work_info', models.CharField(default='', max_length=5000)),
            ],
            options={
                'verbose_name': 'День практики в дневнике без gamification и без mindfullness',
                'verbose_name_plural': 'Дни практики в дневнике без gamification и без mindfullness',
            },
        ),
        migrations.CreateModel(
            name='ClassicPractice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_type', models.CharField(choices=[('Учебная', 'Учебная'), ('Производственная', 'Производственная')], max_length=30, verbose_name='Тип практики')),
                ('practice_addres', models.CharField(default='', max_length=500)),
                ('date_start', models.DateField(default=datetime.datetime(2020, 5, 10, 18, 25, 6, 323455))),
                ('date_end', models.DateField(default=datetime.datetime(2020, 5, 10, 18, 25, 6, 323487))),
            ],
            options={
                'verbose_name': 'Практика без gamification и без mindfullness',
                'verbose_name_plural': 'Практики без gamification и без mindfullness',
            },
        ),
    ]
