# Generated by Django 3.0 on 2019-12-18 19:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DiaryDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2019, 12, 18, 19, 7, 58, 489491))),
                ('work_info', models.CharField(default='', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_type', models.CharField(choices=[('Учебная', 'Учебная'), ('Производственная', 'Производственная')], max_length=30, verbose_name='Type')),
                ('practice_addres', models.CharField(default='', max_length=500)),
                ('date_start', models.DateField(default=datetime.datetime(2019, 12, 18, 19, 7, 58, 490668))),
                ('date_end', models.DateField(default=datetime.datetime(2019, 12, 18, 19, 7, 58, 490688))),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.Diary')),
            ],
        ),
        migrations.AddField(
            model_name='diary',
            name='diary_days',
            field=models.ManyToManyField(to='practice.DiaryDay'),
        ),
    ]
