# Generated by Django 3.0 on 2019-12-18 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryday',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 12, 18, 19, 14, 7, 518282)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2019, 12, 18, 19, 14, 7, 519505)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2019, 12, 18, 19, 14, 7, 519487)),
        ),
    ]
