# Generated by Django 2.2.3 on 2020-04-15 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Teacher'),
        ),
        migrations.AddField(
            model_name='diary',
            name='diary_days',
            field=models.ManyToManyField(to='practice.DiaryDay'),
        ),
    ]
