# Generated by Django 2.2.3 on 2020-05-10 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practice', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classicpractice',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Teacher'),
        ),
        migrations.AddField(
            model_name='classicdiary',
            name='diary_days',
            field=models.ManyToManyField(to='practice.ClassicDiaryDay'),
        ),
        migrations.AddField(
            model_name='classicdiary',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='practice.ClassicPractice'),
        ),
    ]
