# Generated by Django 2.2.3 on 2019-12-19 19:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_student_practices'),
        ('practice', '0002_auto_20191218_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Teacher'),
        ),
        migrations.AlterField(
            model_name='diaryday',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 12, 19, 22, 24, 8, 106572)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2019, 12, 19, 22, 24, 8, 158797)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2019, 12, 19, 22, 24, 8, 158771)),
        ),
    ]
