# Generated by Django 2.2.3 on 2020-04-15 17:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_auto_20200415_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice',
            name='diary',
        ),
        migrations.AddField(
            model_name='diary',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='practice.Practice'),
        ),
        migrations.AlterField(
            model_name='diaryday',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 15, 20, 44, 14, 692606)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2020, 4, 15, 20, 44, 14, 750495)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2020, 4, 15, 20, 44, 14, 750468)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='practice_type',
            field=models.CharField(choices=[('Учебная', 'Учебная'), ('Производственная', 'Производственная')], max_length=30, verbose_name='Тип практики'),
        ),
    ]
