# Generated by Django 2.2.3 on 2020-05-27 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_auto_20200512_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classicdiaryday',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 27, 17, 26, 23, 561083)),
        ),
        migrations.AlterField(
            model_name='classicpractice',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2020, 5, 27, 17, 26, 23, 583529)),
        ),
        migrations.AlterField(
            model_name='classicpractice',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2020, 5, 27, 17, 26, 23, 583509)),
        ),
    ]
