# Generated by Django 2.2.3 on 2020-04-16 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_auto_20200415_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryday',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 16, 20, 28, 53, 517144)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2020, 4, 16, 20, 28, 53, 539942)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2020, 4, 16, 20, 28, 53, 539920)),
        ),
    ]
