# Generated by Django 2.2.3 on 2019-12-26 21:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_auto_20191219_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryday',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 12, 27, 0, 0, 46, 965615)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2019, 12, 27, 0, 0, 47, 28607)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2019, 12, 27, 0, 0, 47, 28582)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='diary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='practice.Diary'),
        ),
    ]
