# Generated by Django 2.2.3 on 2020-03-19 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0005_auto_20191227_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryday',
            name='day_evaluation',
            field=models.IntegerField(blank=True, choices=[(1, 'Понравилось'), (2, 'Не понравилось'), (3, 'Нейтрально')], null=True, verbose_name='Day evaluation'),
        ),
        migrations.AddField(
            model_name='diaryday',
            name='disliked_things',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='diaryday',
            name='liked_things',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='diaryday',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 3, 19, 21, 54, 50, 439621)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2020, 3, 19, 21, 54, 50, 516878)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2020, 3, 19, 21, 54, 50, 516848)),
        ),
    ]
