# Generated by Django 2.2.3 on 2020-05-10 15:25

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('patronymic', models.CharField(default='', max_length=100, verbose_name='Отчество')),
                ('position', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ClassicStudent',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('patronymic', models.CharField(default='', max_length=100, verbose_name='Отчество')),
                ('group', models.CharField(default='', max_length=10, verbose_name='Учебная группа')),
                ('practices', models.ManyToManyField(blank=True, null=True, to='practice.ClassicPractice', verbose_name='Наборы практик')),
            ],
            options={
                'verbose_name': 'Студент без осознанности и геймификации',
                'verbose_name_plural': 'Студенты без осознанности и геймификации',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
