# Generated by Django 2.2.3 on 2020-04-16 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_auto_20200416_2028'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPractice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(default='', verbose_name='Отзыв о практике')),
                ('aim', models.TextField(default='', verbose_name='Цель на практику')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.Practice', verbose_name='Практика')),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.CharField(default='', max_length=10, verbose_name='Учебная группа'),
        ),
        migrations.AlterField(
            model_name='student',
            name='patronymic',
            field=models.CharField(default='', max_length=100, verbose_name='Отчество'),
        ),
        migrations.RemoveField(
            model_name='student',
            name='practices',
        ),
        migrations.AddField(
            model_name='student',
            name='practices',
            field=models.ManyToManyField(blank=True, null=True, through='user.StudentPractice', to='practice.Practice', verbose_name='Наборы практик'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='patronymic',
            field=models.CharField(default='', max_length=100, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='studentpractice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Student', verbose_name='Студент'),
        ),
    ]
