# Generated by Django 3.0 on 2019-12-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_auto_20191218_1914'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='practices',
            field=models.ManyToManyField(blank=True, null=True, to='practice.Practice'),
        ),
    ]
