# Generated by Django 2.2.3 on 2020-05-27 14:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_auto_20200512_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamificationdiary',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gamification.GamificationStudentPractice'),
        ),
        migrations.AlterField(
            model_name='gamificationdiaryday',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 27, 17, 26, 23, 561083)),
        ),
        migrations.AlterField(
            model_name='gamificationpractice',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2020, 5, 27, 17, 26, 23, 583529)),
        ),
        migrations.AlterField(
            model_name='gamificationpractice',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2020, 5, 27, 17, 26, 23, 583509)),
        ),
    ]
